name: Listmonk RSS Campaign

on:
  schedule:
    - cron: '00 8 * * 4'  # Run every Thursday at 8:00 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv and enable caching
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install
          
    - name: 👷 Run RSS campaign
      run: uv run python listmonk_rss.py
      env:
        RSS_FEED: ${{ vars.RSS_FEED }}
        LISTMONK_API_USER: ${{ vars.LISTMONK_API_USER }}
        LISTMONK_API_TOKEN: ${{ secrets.LISTMONK_API_TOKEN }}
        PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
        PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
        LISTMONK_HOST: ${{ vars.LISTMONK_HOST }}
        LIST_NAME: ${{ vars.LIST_NAME }}
        DELAY_SEND_MINS: ${{ vars.DELAY_SEND_MINS }}
        GH_REPOSITORY: ${{ vars.GH_REPOSITORY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
